package gui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.BorderLayout;
import java.awt.FlowLayout;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.NhanVien_DAO;
import entity.NhanVien;

import java.awt.LayoutManager;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author admin
 */
public class JPanel_TraCuuNhanVien extends javax.swing.JPanel implements MouseListener{
	 private NhanVien_DAO nhanVien_dao;
	 private ArrayList<NhanVien> listNhanVien;
	 private DefaultTableModel mode_NhanVien;

	/**
     * Creates new form JPanelTraCuuNhanVien
     */
    public JPanel_TraCuuNhanVien() {
    	try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		nhanVien_dao = new NhanVien_DAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	Border blackline = BorderFactory.createTitledBorder("Thông tin tra cứu");
    	Border blackline1 = BorderFactory.createTitledBorder("Danh sách nhân viên");
        JPanel panel = new JPanel();
        LayoutManager layout = new FlowLayout();  
        lbltitleDanhSach1 = new javax.swing.JLabel();
        khung1 = new javax.swing.JPanel();
        txtTen = new javax.swing.JTextField();
        txtTen.setBounds(170, 61, 300, 30);
        cbbChucVu = new javax.swing.JComboBox<>();
        cbbChucVu.setBounds(779, 98, 300, 30);
        txtSDT = new javax.swing.JTextField();
        txtSDT.setBounds(170, 138, 300, 30);
        lblhoTen = new javax.swing.JLabel();
        lblhoTen.setBounds(16, 63, 105, 20);
        lblgioiTinh = new javax.swing.JLabel();
        lblgioiTinh.setBounds(16, 101, 66, 20);
        txtCCCD = new javax.swing.JTextField();
        txtCCCD.setBounds(779, 61, 300, 30);
        lblCCCD = new javax.swing.JLabel();
        lblCCCD.setBounds(657, 58, 45, 30);
        lblsoDienThoai = new javax.swing.JLabel();
        lblsoDienThoai.setBounds(16, 140, 98, 20);
        lblchucVu = new javax.swing.JLabel();
        lblchucVu.setBounds(653, 96, 63, 30);
        cbbGioiTinh = new javax.swing.JComboBox<>();
        cbbGioiTinh.setBounds(170, 98, 300, 30);
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbltitleDanhSach = new javax.swing.JLabel();



        txtTen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTen.setPreferredSize(new java.awt.Dimension(64, 25));

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên ", "Quản  lý" }));
        cbbChucVu.setPreferredSize(new java.awt.Dimension(72, 20));
        cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucVuActionPerformed(evt);
            }
        });

        txtSDT.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSDT.setPreferredSize(new java.awt.Dimension(64, 25));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        lblhoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblhoTen.setText("Tên nhân viên :");

        lblgioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblgioiTinh.setText("Giới tính :");

        txtCCCD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCCCD.setPreferredSize(new java.awt.Dimension(64, 25));

        lblCCCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCCCD.setText("CCCD :");

        lblsoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblsoDienThoai.setText("Số điện thoại :");

        lblchucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblchucVu.setText("Chức vụ :");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.setPreferredSize(new java.awt.Dimension(72, 20));
        cbbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioiTinhActionPerformed(evt);
            }
        });
        String spaces = " ";
        JLabel label = new JLabel(spaces + "Thông tin tra cưu" + spaces);
        label.setBounds(0, 0, 0, 0);
        khung1.add(label);  
        khung1.setBorder(blackline);

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(51, 51, 51));
        btnThem.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\add25.png")); // NOI18N
        btnThem.setText("Tìm");
        btnThem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.setPreferredSize(new java.awt.Dimension(110, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\refresh25.png")); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(110, 30));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(mode_NhanVien = new DefaultTableModel(
            new Object [][] {
             
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Giới tính", "CCCD", "Chức vụ ", "Trạng thái", "Số điện thoại", "Địa chỉ"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(205, 209, 238));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1063, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 299, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(28, Short.MAX_VALUE))
        );
        String spaces1 = " ";
        jPanel1.add(new JLabel(spaces1 + "Thông tin tra cứu" + spaces1));  
        jPanel1.setBorder(blackline1);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout1 = new javax.swing.GroupLayout(this);
        layout1.setHorizontalGroup(
        	layout1.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout1.createSequentialGroup()
        			.addGap(347)
        			.addComponent(btnThem, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        			.addGap(314)
        			.addComponent(btnLamMoi, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        			.addGap(0, 270, Short.MAX_VALUE))
        		.addGroup(layout1.createSequentialGroup()
        			.addGap(62)
        			.addGroup(layout1.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout1.createSequentialGroup()
        					.addComponent(lbltitleDanhSach1)
        					.addGap(0, 1119, Short.MAX_VALUE))
        				.addGroup(layout1.createSequentialGroup()
        					.addComponent(lbltitleDanhSach)
        					.addContainerGap(1119, Short.MAX_VALUE))
        				.addGroup(layout1.createSequentialGroup()
        					.addGroup(layout1.createParallelGroup(Alignment.TRAILING)
        						.addComponent(khung1, GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
        						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGap(76))))
        );
        layout1.setVerticalGroup(
        	layout1.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout1.createSequentialGroup()
        			.addGap(19)
        			.addComponent(lbltitleDanhSach1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(khung1, GroupLayout.PREFERRED_SIZE, 237, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout1.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnThem, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnLamMoi, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lbltitleDanhSach)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 349, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khung1.setLayout(null);
        khung1.add(label);
        khung1.add(lblhoTen);
        khung1.add(lblgioiTinh);
        khung1.add(lblsoDienThoai);
        khung1.add(cbbGioiTinh);
        khung1.add(lblchucVu);
        khung1.add(cbbChucVu);
        khung1.add(txtTen);
        khung1.add(lblCCCD);
        khung1.add(txtCCCD);
        khung1.add(txtSDT);
        this.setLayout(layout1);
        
        jTable1.addMouseListener(this);
        loadNhanVien();
    }// </editor-fold>                        
    private void cbbChucVuActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void cbbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	lamMoi();
    }              
    public void loadNhanVien() {
  		listNhanVien = nhanVien_dao.getAllNhanVien();
  		
  		for (NhanVien nv: listNhanVien) {
  			String gt ="Nữ";
  			if(nv.getGioiTinh()==1) {
  				gt ="Nam";
  			}
  			mode_NhanVien.addRow(new Object[] { 
  					nv.getMaNhanVien(), nv.getTenNhanVien() ,
  					nv.getNgaySinh(),gt,
  					nv.getcCCD(), nv.getChucVu(),nv.getTrangThai(), 
  					nv.getSoDienThoai(),nv.getDiaChi() });
  		}
  	}
    public void lamMoi() {
    	txtTen.setText("");
    	txtCCCD.setText("");
    	JDateNgaySinh.setDate(null);
    	txtSDT.setText("");
    	cbbGioiTinh.setSelectedIndex(0);
    	cbbChucVu.setSelectedIndex(0);
    	mode_NhanVien.setRowCount(0);
    	txtTen.requestFocus();
    	loadNhanVien();
    	
    }
    public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		int r = jTable1.getSelectedRow();
		txtTen.setText(mode_NhanVien.getValueAt(r, 1).toString());
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
		Date date = null;
		try {
			date = format.parse(mode_NhanVien.getValueAt(r, 2).toString());
		} catch (ParseException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		JDateNgaySinh.setDate(date);
		cbbGioiTinh.setSelectedItem(mode_NhanVien.getValueAt(r, 3));
		txtCCCD.setText(mode_NhanVien.getValueAt(r, 4).toString());
		cbbChucVu.setSelectedItem(mode_NhanVien.getValueAt(r, 5));
		txtSDT.setText(mode_NhanVien.getValueAt(r, 7).toString());
		requestFocus();
		
		
		
	}
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTable jTable1;
    private javax.swing.JPanel khung1;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblchucVu;
    private javax.swing.JLabel lblgioiTinh;
    private javax.swing.JLabel lblhoTen;
    private javax.swing.JLabel lblsoDienThoai;
    private javax.swing.JLabel lbltitleDanhSach;
    private javax.swing.JLabel lbltitleDanhSach1;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}
    

    // End of variables declaration                   
}
