/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author tranvanloi
 */
public class JPanel_ThanhToanHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form Jpanel_ThanhToanHoaDon
     */
    public JPanel_ThanhToanHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblThongTinHoaDon = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();
        lblGioVao = new javax.swing.JLabel();
        lblGioRa = new javax.swing.JLabel();
        lblNgayTaoHoaDon = new javax.swing.JLabel();
        lblTongTienThanhToan = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        lblTienDichVu = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblTienNhan = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        lblMaHoaDon1 = new javax.swing.JLabel();
        lblPhong1 = new javax.swing.JLabel();
        lblGioVao1 = new javax.swing.JLabel();
        lblGioRa1 = new javax.swing.JLabel();
        lblTienDichVu1 = new javax.swing.JLabel();
        lblNgayTaoHoaDon1 = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        lblTienPhong1 = new javax.swing.JLabel();
        lblTienNhan1 = new javax.swing.JLabel();
        lblTienThua1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblThongTinKhachHang = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        cmTenDichVu = new javax.swing.JComboBox<>();
        lblTenDichVu = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        cmbSoLuong = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ChiTietDichVu = new javax.swing.JTable();
        lblChiTietDichVu = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        lblThongTinNhanVien = new javax.swing.JLabel();
        lblTenKhachHang1 = new javax.swing.JLabel();
        lblMaNhanVien1 = new javax.swing.JLabel();
        lblTenNhanVien1 = new javax.swing.JLabel();
        lblCCCD1 = new javax.swing.JLabel();
        lblThanhToanHoaDon = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1250, 755));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblThongTinHoaDon.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblThongTinHoaDon.setText("Thông tin hoá đơn");

        lblMaHoaDon.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblMaHoaDon.setText("Mã hoá đơn :");

        lblPhong.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblPhong.setText("Phòng :         ");

        lblGioVao.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblGioVao.setText("Giờ vào:");

        lblGioRa.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblGioRa.setText("Giờ ra:");

        lblNgayTaoHoaDon.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblNgayTaoHoaDon.setText("Ngày tạo hoá đơn :");

        lblTongTienThanhToan.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTongTienThanhToan.setText("Tổng tiền thanh toán");

        lblTienPhong.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienPhong.setText("Tiền phòng :");

        lblTienDichVu.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienDichVu.setText("Tiền dịch vụ :");

        lblTongTien.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTongTien.setText("Tổng tiền :");

        lblTienNhan.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienNhan.setText("Tiền nhận :");

        lblTienThua.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTienThua.setText("Tiền thừa :");

        btnThanhToan.setBackground(new java.awt.Color(162, 74, 74));
        btnThanhToan.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setIcon(new javax.swing.ImageIcon("item/1490863900_paypal.png")); // NOI18N
        btnThanhToan.setText("Thanh toán\n");
        btnThanhToan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnInHoaDon.setBackground(new java.awt.Color(162, 74, 74));
        btnInHoaDon.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btnInHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnInHoaDon.setIcon(new javax.swing.ImageIcon("item/print-24.png")); // NOI18N
        btnInHoaDon.setText("In hoá đơn\n");
        btnInHoaDon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMaHoaDon1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblMaHoaDon1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblPhong1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblPhong1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblGioVao1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblGioVao1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblGioRa1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblGioRa1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienDichVu1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienDichVu1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblNgayTaoHoaDon1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblNgayTaoHoaDon1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTongTien1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTongTien1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienPhong1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienPhong1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienNhan1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienNhan1.setPreferredSize(new java.awt.Dimension(42, 25));

        lblTienThua1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTienThua1.setPreferredSize(new java.awt.Dimension(42, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGioVao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addComponent(lblMaHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTienThua1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTienNhan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTienPhong1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTongTien1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTienDichVu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblGioRa)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayTaoHoaDon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGioRa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGioVao)
                                        .addComponent(lblNgayTaoHoaDon)
                                        .addComponent(lblMaHoaDon)
                                        .addComponent(lblPhong)))
                                .addComponent(lblTongTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTongTien)
                                    .addComponent(lblTienThua)
                                    .addComponent(lblTienNhan))
                                .addComponent(lblTienPhong)
                                .addComponent(lblTienDichVu))))
                    .addContainerGap(136, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblMaHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGioVao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioRa)
                    .addComponent(lblGioRa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNgayTaoHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTienPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTienDichVu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTienNhan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTienThua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(lblThongTinHoaDon)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(lblPhong)
                            .addGap(23, 23, 23)
                            .addComponent(lblGioVao))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblMaHoaDon)))
                    .addGap(54, 54, 54)
                    .addComponent(lblNgayTaoHoaDon)
                    .addGap(66, 66, 66)
                    .addComponent(lblTongTienThanhToan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblTienPhong)
                    .addGap(18, 18, 18)
                    .addComponent(lblTienDichVu)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblTongTien)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblTienNhan)
                    .addGap(18, 18, 18)
                    .addComponent(lblTienThua)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblThongTinKhachHang.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblThongTinKhachHang.setText("Thông tin khách hàng");

        btnCapNhat.setBackground(new java.awt.Color(162, 74, 74));
        btnCapNhat.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon("item/update25.png")); // NOI18N
        btnCapNhat.setText("Cập nhật\n");
        btnCapNhat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setBackground(new java.awt.Color(162, 74, 74));
        btnThem.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon("item/add25.png")); // NOI18N
        btnThem.setText("Thêm\n");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmTenDichVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmTenDichVu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmTenDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmTenDichVuActionPerformed(evt);
            }
        });

        lblTenDichVu.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        lblTenDichVu.setText("Tên dịch vụ :");

        lblSoLuong.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        lblSoLuong.setText("Số lượng:");

        cmbSoLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSoLuong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSoLuongActionPerformed(evt);
            }
        });

        tbl_ChiTietDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên dịch vụ", "Số lượng", "Giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ChiTietDichVu.setGridColor(new java.awt.Color(220, 155, 155));
        jScrollPane1.setViewportView(tbl_ChiTietDichVu);

        lblChiTietDichVu.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblChiTietDichVu.setText("Chi tiết dịch vụ");

        lblMaNhanVien.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên :");

        lblTenNhanVien.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTenNhanVien.setText("Tên nhân viên :");

        lblCCCD.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblCCCD.setText("CCCD :");

        lblTenKhachHang.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblTenKhachHang.setText("Tên khách hàng :");

        btnXoa.setBackground(new java.awt.Color(162, 74, 74));
        btnXoa.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon("item/delete25.png")); // NOI18N
        btnXoa.setText("Xoá\n");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblThongTinNhanVien.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblThongTinNhanVien.setText("Thông tin nhân viên");

        lblTenKhachHang1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTenKhachHang1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblTenKhachHang1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblMaNhanVien1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblMaNhanVien1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblMaNhanVien1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblTenNhanVien1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblTenNhanVien1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblTenNhanVien1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblCCCD1.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblCCCD1.setPreferredSize(new java.awt.Dimension(42, 30));
        lblCCCD1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTenKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCCCD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCCCD1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongTinKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThongTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(lblTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblThongTinKhachHang)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKhachHang)
                            .addComponent(lblCCCD)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblTenKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblCCCD1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(lblThongTinNhanVien)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNhanVien)
                            .addComponent(lblTenNhanVien)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(527, 527, 527)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTenDichVu)
                        .addComponent(cmTenDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong)
                        .addComponent(cmbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        lblThanhToanHoaDon.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        lblThanhToanHoaDon.setText("Thanh Toán Hoá Đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblThanhToanHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblThanhToanHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cmTenDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmTenDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmTenDichVuActionPerformed

    private void cmbSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSoLuongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmTenDichVu;
    private javax.swing.JComboBox<String> cmbSoLuong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblCCCD1;
    private javax.swing.JLabel lblChiTietDichVu;
    private javax.swing.JLabel lblGioRa;
    private javax.swing.JLabel lblGioRa1;
    private javax.swing.JLabel lblGioVao;
    private javax.swing.JLabel lblGioVao1;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaHoaDon1;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMaNhanVien1;
    private javax.swing.JLabel lblNgayTaoHoaDon;
    private javax.swing.JLabel lblNgayTaoHoaDon1;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblPhong1;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDichVu;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTenKhachHang1;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTenNhanVien1;
    private javax.swing.JLabel lblThanhToanHoaDon;
    private javax.swing.JLabel lblThongTinHoaDon;
    private javax.swing.JLabel lblThongTinKhachHang;
    private javax.swing.JLabel lblThongTinNhanVien;
    private javax.swing.JLabel lblTienDichVu;
    private javax.swing.JLabel lblTienDichVu1;
    private javax.swing.JLabel lblTienNhan;
    private javax.swing.JLabel lblTienNhan1;
    private javax.swing.JLabel lblTienPhong;
    private javax.swing.JLabel lblTienPhong1;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTienThua1;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JLabel lblTongTienThanhToan;
    private javax.swing.JTable tbl_ChiTietDichVu;
    // End of variables declaration//GEN-END:variables
}
